### ISSUE TITLE
[Suggestion] Cogs

### ISSUE THREAD

**Issue by Motzumoto** [InfinityBots/InfinityBotsGuide#2]
Examples of both Post and Get examples for cogs, having the basic bot, client.event / command examples are excluding a huge chunk of other devs who dont use that.

**Comment by TheRealToxicDev** [comment]
> Examples of both Post and Get examples for cogs, having the basic bot, client.event / command examples are excluding a huge chunk of other devs who dont use that.

Adding the code to your cogs or whatever is up to the user to figure out not hard to do, we aren’t gonna spoon feed code it’s just a basic example 🤷🏻‍♂️

**Comment by TheRealToxicDev** [comment]
This is also something that should be brought up with the maintainer of the module 😀 I just make and manage the docs

**Comment by Motzumoto** [comment]
> This is also something that should be brought up with the maintainer of the module 😀 I just make and manage the docs

If you dont make any of the code then where was the need to reply? You're using a super basic version of dpy, which as i stated above, is excluding a huge chunk of developers, " we aren’t gonna spoon feed code", a lot of developers such as myself dont know how to convert the code that you use

**Comment by cheesycod** [comment]
@Motzumoto I believe the new IBLPy does a client.event example and a no dpy example as well.

As for cogs, I can add it to the new IBLPy documentation

**Comment by Motzumoto** [comment]
> @Motzumoto I believe the new IBLPy does a client.event example and a no dpy example as well.
> 
> As for cogs, I can add it to the new IBLPy documentation

I was actually recently banned from IBL for "api abuse". Dunno really, don't think that a 3 minute cooldown is api abuse but to each their own. Thanks for responding though.

**Comment by cheesycod** [comment]
> > @Motzumoto I believe the new IBLPy does a client.event example and a no dpy example as well.
> > As for cogs, I can add it to the new IBLPy documentation
> 
> I was actually recently banned from IBL for "api abuse". Dunno really, don't think that a 3 minute cooldown is api abuse but to each their own. Thanks for responding though.

Pretty sure the ratelimit is 3 requests per 5 minutes so a 3 minute cooldown could be insufficient

**Comment by Motzumoto** [comment]
> > > @Motzumoto I believe the new IBLPy does a client.event example and a no dpy example as well.
> > > As for cogs, I can add it to the new IBLPy documentation
> > 
> > I was actually recently banned from IBL for "api abuse". Dunno really, don't think that a 3 minute cooldown is api abuse but to each their own. Thanks for responding though.
> 
> Pretty sure the ratelimit is 3 requests per 5 minutes so a 3 minute cooldown could be insufficient 

oh no no no, not even requesting for posting stats, Discord API ratelimits.
